data: '/rap/jvb-000-aa/COURS2019/etudiants/data/omsignal/myHeartProject/'
preprocessing:
  noise_gain: 0.25
dataloader:
  test_proportion: 0.2
  batch_size: 64
  shuffle: True
  num_workers: 6
models:
  tspec:
    ts_len: 3750
    spec_len: 1876
    hid_dim: 100
    num_layers: 3
    out_dims:
      - 1
      - 1
      - 1
      - 32
training:
  schedule_patience: 20
  early_stopping_patience: 100
  epochs: 1000
  learning_rate: 0.01
  momentum: 0.9
  l2: 0.01
